#!/usr/bin/env bash

# TODO: output directory

# the video files to convert
extensions=(".flv" ".mpg" ".mpeg" ".mpe" ".mov" ".avi" ".mkv" ".asf" ".wmv" ".rmvb" ".webm")
# remove trailing slashes
location=$(dirname "$1")/$(basename "$1")

# find the available extensions
# find "$location" -type f -print0 | xargs -0 basename | awk -F. '{ print $(NF) }' | sort -u

# convert to mp4
function convert {
  dname=$(dirname "$1")
  bname=$(basename "$1" "$2")
  # mirror the folder structure locally
  folder="${dname/$location/.}"
  if [ "$folder" != "." ]; then
    mkdir -p "$folder"
  fi
  # clobbers stdin so pass in /dev/null
  ffmpeg -i "$1" $3 -q:v 0 -c:v libx264 -c:a libfaac "${folder}/${bname}.mp4" < /dev/null
}

# copy over the mp4 files first if not there
while read -r file; do
  dname=$(dirname "$file")
  bname=$(basename "$file")
  # mirror the folder structure locally
  folder="${dname/$location/.}"
  if [ "$folder" != "." ]; then
    mkdir -p "$folder"
  fi
  target="${folder}/${bname}"
  # only copy if file is not there
  if [ -f "$target" ]; then
    cp -v "$file" "$target"
  fi
done <<< "$(find "$location" -type f -name "*.mp4")"

# convert to the -o -name structure that find uses for find multiple files
# so there we don't have to loop for each file extension
searchnames=""
for ext in "${extensions[@]/#/*}"; do
  searchnames="${searchnames} -o -name \"$ext\""
done
# remove the first -o
searchnames="${searchnames:4}"

# first attempt convert what is not there
while read -r file; do
  convert "$file" "$ext"
done <<< "$(find "$location" -type f $searchnames)"

# second attempt assume it was a not divisble by 2 error, attempt to fix
while read -r file; do
  name=$(basename "$file" ".mp4")
  # attempt to find the original to convert
  for ext in "${extensions[@]}"; do
    original="$(find "$location" -type f -name "${name}${ext}")"
    if [ "$original" != "" ]; then
      # assume height not divisble by 2 error and attempt to round down 1 pixel
      # force overwrite (-y)
      convert "$original" "$ext" "-vf scale='trunc(iw/2)*2:trunc(ih/2)*2' -y"
      break
    fi
  done
# failure results in a 0 byte file, take advantage to reconvert
done <<< "$(find . -type f -size 0)"

# TODO: Remove files that are no longer in original location
